global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'app-agent'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8081' ]

  - job_name: 'redis-exporter'
    static_configs:
    - targets: [ 'redis-exporter:9121' ]

  - job_name: 'kafka'
    static_configs:
    - targets: [ 'kafka-exporter:9308' ]
    metrics_path: /metrics
